<a href="https://colab.research.google.com/github/ravitejaboddula/Numpy/blob/main/Numpy_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [23]:
import numpy as np

In [24]:
arr = np.array([2,3,4])
print(arr)

[2 3 4]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
a = np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#get dimensions
b.ndim

2

In [ ]:
#to get shape
b.shape

(2, 3)

In [ ]:
#to get in how many bits the data is stored
a.dtype

dtype('int8')

In [27]:
#to get how many bytes the data is stored
a.itemsize

1

In [ ]:
#to get the number of elements in array
b.size

6

In [ ]:
#like to get the total bytes of array number_of_elements * number of bytes per an item
b.size * b.itemsize

48

In [ ]:
#like instaed to get total bytes
b.nbytes

48

Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#to get an sepecific element
a[1,5]

np.int64(13)

In [ ]:
#to get the specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#to get the sepecific col
a[:,3]

array([ 4, 11])

In [ ]:
#for like start, end and step from matrics [startindex : endindex: step]
a[1:6:2]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-D examples

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#to get sepecific element
b[1,1,0]

np.int64(7)

In [ ]:
#replace
b[1,1,1] = 9
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


Initializing Different Types of Arrays

In [ ]:
#to get the All Zeros
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#to get the All ones
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#to get the any other number
other = np.full((2,3), 5)
other

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
#to get any other number(full like)
like = np.full_like(ones,5)
like

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
#to get the random numbers the parameters are size of matrix
ran = np.random.rand(2,3)
print(ran)

[[0.13629887 0.98730001 0.38230921]
 [0.71174581 0.09994811 0.01998391]]


In [ ]:
#to get the random integer value the parameters are size of matrix
r = np.random.randint(2,9, (2,5))
print(r)

[[8 4 2 4 3]
 [5 2 5 8 3]]


In [ ]:
#to indentity matrix. indetity matrix means the diagonal should be all ones and other are all zeros
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#to repeat the arrays
arr = np.array([[1,2,3]])
arr = arr.repeat(3,axis=0)
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import numpy as np
arr = np.ones((5,5), dtype='int8')
arr[1:4,1:4] = 0
arr[2,2] = 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[2] = 5
print(a)

[1 2 3]


Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a  * 2

array([2, 4, 6, 8])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
#to get the cos, tan , coesc
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

####Linear Algebra

In [3]:
import numpy as np

In [6]:
#we can not to do like arr1 * arr2 like diff dimensions but we can use the
#matmul for the multiplication of two diff dimension arrays
a = np.ones((2,3))
b = np.full((3,2), 5)

new = np.matmul(a,b)
print(new)

[[15. 15.]
 [15. 15.]]


In [7]:
#to find the determinant
c = np.identity(3)
np.linalg.det(c)


np.float64(1.0)

#Statistics

In [16]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#to get the min
np.min(stats)

np.int64(1)

In [18]:
#to get the max
np.max(stats)

np.int64(6)

In [19]:
#to get the whole sum of array
np.sum(stats)

np.int64(21)

In [20]:
#to get the whole mean of array
np.mean(stats)

np.float64(3.5)

In [22]:
#to get the median
np.median(stats)

np.float64(3.5)

In [15]:
import numpy as np

matrix = np.array([[4, 5, 6],
                  [1,2,3]])

print(np.max(np.sum(matrix, axis=0)))

print(np.min(np.sum(matrix, axis=1)))


9
6


Reorganizing an array

In [32]:
#reshaping the arrays while reshaping the new shape should fit the all the elements of previous shape data no less and no morev1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
before = np.array([[2,3,4,4],[2,4,5,6]])

after = before.reshape((2,4))
after

array([[2, 3, 4, 4],
       [2, 4, 5, 6]])

In [35]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
#horizontal stacking of vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

Miscellaneous

Load Data from File